name: First Workflow
on: workflow_dispatch
jobs: 
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello mate!"
      - name: say goodbye
        run: echo "Bye mate!"
